services:
    Nahoy\ApiPlatform\ConsumptionBundle\EventSubscriber\ConsumptionPusherSubscriber:
        arguments:
            - "@nahoy_api_platform_consumption.service.cache"
            - "@security.untracked_token_storage"
            - "@router"
            - "%nahoy_api_platform_consumption.api_pattern%"
            - "%nahoy_api_platform_consumption.getter.user_id%"
            - "%nahoy_api_platform_consumption.getter.user_username%"
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 12 }

    nahoy_api_platform_consumption.service.cache:
        class: Nahoy\ApiPlatform\ConsumptionBundle\Service\CacheService
        arguments:
            - ~
        public: true
